### ISSUE TITLE
No themes available.

### ISSUE THREAD

**Issue by rlabbe** [lgienapp/aquarel#1]
I just did a pip install.

    from aquarel import list_themes
    list_themes()

returns

    []

and load_theme("arctic_light")

raises

     ValueError: No theme named 'arctic_light' found.

Windows 11, Anaconda Python 3.9 installation. 

I stepped into the code, it is globbing 'C:\\anaconda3\\lib\\site-packages\\aquarel\\themes\\*.json', but there is no
themes subdirectory in 'C:\\anaconda3\\lib\\site-packages\\aquarel\, and a search of my drive confirms that arctic_light.json is not anywhere on my drive. 

As an aside, I recommend using os.path.join to create the filepath, you have hardcoded in unix style with f"{loc}/themes/*.json"

    os.path.join(loc, 'themes', '*.json')

**Comment by lgienapp** [comment]
Ah, I forgot to include the JSON files in `setup.py`, should be fixed now. Ill look into the path issue later, thanks for the suggestion. I guess this breaks the paths on Windows?
