### ISSUE TITLE
Arial font not included in the package?

### ISSUE THREAD

**Issue by realliyifei** [lgienapp/aquarel#36]
`WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial`

**Comment by lgienapp** [comment]
Fonts are not included in the package, as managing font files is out of scope. In your case, please install the `Arial` font on your system, or overwrite the font choice of the theme by calling `.set_font(family=...)` .

**Comment by lgienapp** [comment]
Please run an ablation to make sure the error is within the scope of `aquarel`: if you replace the `with load_theme(...):` line with the pure matplotlib [rcParams](https://matplotlib.org/stable/api/matplotlib_configuration_api.html#matplotlib.RcParams) call `mpl.rcParams['font.family'] = ...`, does the error persist? If not, I will keep this issue closed, as no change to aquarel could fix it.

**Comment by aaronjbecker** [comment]
I ran into the same issue (running on Ubuntu) and manually calling `mpl.rcParams['font.family'] = ...` did make the issue go away while using `theme = theme.set_font(family="...")` did not.  This does seem to be an issue within this library. I don't have this issue on my mac laptop, only on linux. 

If I add a call to `mpl.rcParams` at the top of the jupyter notebook after applying the theme I don't have any problems. Great library overall! Way better than the seaborn themes I had been using.
